version: '3'

services:
  www:
    build: .
    ports:
      - 8080:80
    environment:
      # please for the love of god, change this
      - ADMIN_LOGIN=admin:admin
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
