version: '3'

services:
  www:
    build: .
    ports:
      - 8080:80
    environment:
      # please for the love of god, change this
      - ADMIN_LOGIN=admin:admin
      # location of all files
      - STORAGE_PATH=/app/storage
      # location info for weather
      - LAT=0.00
      - LON=0.00
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
